default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: party_maker_development

test:
  <<: *default
  database: party_maker_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %> #это добавлено для деплоя на railway.app
  database: party_maker_production
  username: party_maker
  password: <%= ENV["PARTY_MAKER_DATABASE_PASSWORD"] %>
